services:
  # 1. FastAPI Machine Learning Engine
  - type: web
    name: momo-ml-engine
    env: python
    rootDir: machine-learning-engine
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn index:app --host 0.0.0.0 --port $PORT
    autoDeploy: true

  # 2. Node.js Express Backend & WebSocket Server
  - type: web
    name: momo-backend-api
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node index.js
    autoDeploy: true
    envVars:
      - key: PORT
        value: 5000
      - key: MONGO_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: ML_ENGINE_URL
        fromService:
          type: web
          name: momo-ml-engine
          envVarKey: RENDER_EXTERNAL_URL
