export const THEME = {
  primary: '#8A0F13',
  primaryDark: '#660B0E',
  primaryLight: '#FEF2F2',
  primaryBorder: '#FDE3E3',
  primaryMuted: '#9B1B20',
  background: '#F5F5F7',
  surface: '#FFFFFF',
  card: '#FFFFFF',
  text: '#171717',
  textSecondary: '#525252',
  textMuted: '#737373',
  border: '#E5E5E5',
  borderLight: '#F0F0F2',
  success: '#16A34A',
  successLight: '#DCFCE7',
  warning: '#D97706',
  warningLight: '#FEF3C7',
  danger: '#DC2626',
  dangerLight: '#FEE2E2',
  teal: '#0D9488',
  tealLight: '#CCFBF1',
  purple: '#7C3AED',
  purpleLight: '#F3E8FF',
  rose: '#E11D48',
  roseLight: '#FFE4E6',
  blue: '#0284C7',
  blueLight: '#E0F2FE',
  gold: '#D97706',
  goldLight: '#FEF3C7',
};

export const FONTS = {
  light: 'Satoshi-Light',
  regular: 'Satoshi-Regular',
  medium: 'Satoshi-Medium',
  bold: 'Satoshi-Bold',
  black: 'Satoshi-Black',
};

export const SHADOWS = {
  card: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
  },
  cardElevated: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 4,
  },
  crimsonGlow: {
    shadowColor: '#8A0F13',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 6,
  },
};
